### ISSUE TITLE
Partial commits

### ISSUE THREAD

**Issue by tulians** [tulians/tm#3]
When partial commits are generated the `merge` method in `git.py` has no changed files to push. So:

1. There must be a flag that indicates that it should not do all the adding as no files will be received.
```
Traceback (most recent call last):
  File ".tm_tasks/tm", line 75, in <module>
    pt.completed_task(identifier)
  File "/Users/tulians/Documents/tm/.tm_tasks/manage.py", line 341, in completed_task
    completed_task.info["identifier"]
  File "/Users/tulians/Documents/tm/.tm_tasks/git.py", line 80, in make
    add_files(files)
  File "/Users/tulians/Documents/tm/.tm_tasks/git.py", line 12, in add_files
    raise ValueError("No files received for adding.")
ValueError: No files received for adding.
```

2. As the partial commit branch is local there is no need to run the remote deletition.
```
error: unable to delete 'partials_test': remote ref does not exist
error: failed to push some refs to 'https://github.com/tulians/tm.git'
```

**EDIT**: done.

**Comment by tulians** [comment]
Take also into account that `menu.py` runs itself from scratch each time its called, so there is no memory of previous actions.
**EDIT**: done.

**Comment by tulians** [comment]
The final commit message should be the one of the task creation, not the partial commits.
